apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: git@gitlab.com:bennie-jr/portfolio-gitops.git
    targetRevision: HEAD
    path: ./apps/fluentd
  destination: 
    server: https://kubernetes.default.svc
    namespace: efk-logging 

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
