{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reciperater
  annotations:
   cert-manager.io/issuer: {{ .Values.issuerName }}
spec:
  tls:
    - hosts:
      - {{ .Values.host }}
      secretName: {{ .Values.issuerName }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: {{ .Values.port }}
        path: /
        pathType: Prefix
  ingressClassName: {{ .Values.ingressClassName }}
{{- end }}