apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginxConfigMapName }}
data:
  nginx.conf: |
    events {}

    http {
        include /etc/nginx/mime.types;

        server {
            listen 80 default_server;

            access_log  /var/log/nginx/domain1.access.log;

            location /static {
                root /usr/share/nginx/html;
                try_files $uri $uri/ @server;
            }

            location / {
                try_files $uri $uri/ index.html index.htm @server;
            }

            location @server {
                proxy_pass         http://localhost:8085;  # Use the upstream directive
                proxy_redirect     off;

                proxy_set_header   Host             $host;
                proxy_set_header   X-Real-IP        $remote_addr;
                proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
            }
        }
    }
